"""empty message

Revision ID: 664883e07e2e
Revises: 
Create Date: 2020-12-01 22:51:52.040983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664883e07e2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quad_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.SmallInteger(), nullable=True),
    sa.Column('boardState', sa.String(length=64), nullable=True),
    sa.Column('p1id', sa.Integer(), nullable=True),
    sa.Column('p2id', sa.Integer(), nullable=True),
    sa.Column('lastEdit', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quad_games')
    # ### end Alembic commands ###
